# Generated by Django 4.2.17 on 2025-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('operation_id', models.UUIDField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payer_inn', models.TextField(max_length=12)),
                ('payment_date', models.DateTimeField()),
                ('status', models.TextField(max_length=30)),
            ],
        ),
    ]
