# Generated by Django 4.2.17 on 2025-06-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_paymenttransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='payment_date',
            new_name='create_date',
        ),
    ]
